version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - rabbitmq
      - redis
      - elasticsearch
    ports:
      - "8000:8000"

  celery-worker:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - rabbitmq
    command: ["celery", "-A", "celery_app", "worker", "--loglevel=info"]

  flower:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rabbitmq
    command: ["celery", "-A", "celery_app", "flower", "--port=5555"]
    ports:
      - "5555:5555"

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  pgdata:
